server {
    listen 80;
    server_name _;
    root /usr/src/app/build;
    index index.html;
    client_max_body_size 10G;

    location / {
        try_files $uri $uri/ /index.html;
        add_header Cache-Control "no-store, no-cache, must-revalidate";
    }
}
