// ACCESS CONSTANTS
const ACCESS_TOKEN = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVkZTc4NDA1ZjNkNjEyMDAxMjUzZjE3OSIsImlhdCI6MTU3Nzk5MTc0OCwiZXhwIjoxNTc4MjUwOTQ4fQ.ntyJqQuuZw-2YQQOkZNAmTNM8A1TzIvhfkz5P_Mgj64";
module.exports.ACCESS_TOKEN = ACCESS_TOKEN

// API CONSTANTS
const API_URI = 'http://aura.dmz.teco.edu/api';
const AUTH_URI = 'http://aura.dmz.teco.edu/auth';
module.exports.API_URI = API_URI
module.exports.AUTH_URI = AUTH_URI

// HTTP METHOD CONSTANTS
let HTTP_METHODS = {}
HTTP_METHODS.GET = 'GET'
HTTP_METHODS.POST = 'POST'
HTTP_METHODS.PUT = 'PUT'
HTTP_METHODS.DELETE = 'DELETE'

module.exports.HTTP_METHODS = HTTP_METHODS

// ENDPOINT CONSTANTS
let ENDPOINTS = {}
ENDPOINTS.DEFAULT = '/'
ENDPOINTS.LABEL_DEFINITIONS = '/labelDefinitions'
ENDPOINTS.LABEL_TYPES = '/labelTypes'
ENDPOINTS.DATASETS = '/datasets'
ENDPOINTS.EXPERIMENTS = '/experiments'

module.exports.ENDPOINTS = ENDPOINTS
